name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.41
        username: appap_ru
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        port: 22
        script: |
          cd SummerPractice
          git pull origin master
          pm2 delete appap_ru
          PORT=3300 pm2 --name appap_ru start npm -- start
          pm2 save
